### ISSUE TITLE
Unclear usage of `add_on_binder`

### ISSUE THREAD

**Issue by lczech** [RosettaCommons/binder#253] opened 2023-01-16 23:18 UTC
Hi there,

the documentation of `binder` and `add_on_binder` [here](https://cppbinder.readthedocs.io/en/latest/config.html#config-file-options) unfortunately does not clarify on how to use this in practice, and the test cases are confusing, so I'm reaching out for some help and insight here.

### Documentation

The documentation says that `add_on_binder` meant to add extra bindings to a `class`/`struct`, but does not specify the function signatures that are needed for that. It just says:

```
+add_on_binder numeric::xyzVector rosetta_binders::xyzVector_add_on_binder
```

Furthermore, in the tests, T50 seems to briefly cover this, with the config file line

```
+add_on_binder_for_namespace aaaa add_on_binder_for_aaaa
```

and an implementation provided as

```
void add_on_binder_for_aaaa(pybind11::module &) {}
```

That however is confusing: If the `add_on_binder` is supposed to add binding code to a `class`, why is the function taking a `pybind11::module` here, and not a `pybind11::class_`? I first thought that a `class_` in pybind might be a type of module or inherited from it, but could not confirm that by looking at the pybind code and documentation.

### Example

The following code for example seems to work fine to add a custom constructor to my Bitvector bindings:

```
// config
+add_on_binder Bitvector bitvector_extra_bindings

// hpp
template<class C>
inline void bitvector_extra_bindings( C& cl )
{
    cl.def( py::init( [](std::vector<bool> const& input){ 
        return Bitvector(input.begin(), input.end()); 
    }), py::arg("values"));
}
```

where I'm using a template function so that it works conveniently with the generated binding for the class:

```
pybind11::class_<Bitvector, std::shared_ptr<Bitvector>>
```

and creates the additional line in the binding

```
bitvector_extra_bindings(cl);
```

which seems correct to me, and works.

### Question

The above example seems to work, but I'm wondering if that's the intended usage. If not, could you please clarify, or extend the documentation with a full example?

Thanks and so long
Lucas (and Giannis)

**Comment by lyskov** [comment] 2023-01-18 22:08
@lczech thank you for pointing this out! I will update docs shortly in meanwhile:

- the `add_on_binder` and `add_on_binder_for_namespace` specify different kind of binders so they take different type of arguments: the `add_on_binder` (which is intended to extend bindings for specified types/family-of-types) will take `pybind11::class_<T>` where `add_on_binder_for_namespace` will take `pybind11::module` as an argument. Idea is that `add_on_binder` relay on Binder to create proper `pybind11::class_` instance for given so we can extend it (like add extra bindings for functions or data members). And for case `add_on_binder_for_namespace` we got namespace instance (also created by Binder generated code) so we can add new types/functions/enums to that namespace. Does this answer your question?

Please let me know if you need more info.

**Comment by lczech** [comment] 2023-01-18 22:29
Thanks @lyskov for the quick answer! 

That clarifies the intention of these config file options, yes. As for the intended usage though: Is the Example above how these are meant to be used then? In particular, my `bitvector_extra_bindings` function above?

Cheers and thanks again
Lucas

**Comment by lyskov** [comment] 2023-01-19 05:16
> As for the intended usage though: Is the Example above how these are meant to be used then? In particular, my `bitvector_extra_bindings` function above?

-- yes, thats the intending usage pattern. Note that for template classes it might be more convenient to use more specific template patters like `template<class T> void bitvector_extra_bindings( pybind11::class_<T, std::shared_ptr<T> >& cl )` which will allow you to use type `T` inside the function. 

Hope this helps,

**Comment by lczech** [comment] 2023-01-19 21:41
Thank you, that's a neat idea! Is binder guaranteed to always generate code that uses the `std::shared_ptr` holder though? Otherwise, that would not be the right function signature, or am I missing something here? I didn't find anything on this in the binder documentation.

**Comment by lyskov** [comment] 2023-01-20 18:38
By default Binder will use `std::shared_ptr` as holder-type unless config option  `+custom_shared` was used to specify different holder type. So if your project is always using `std::shared_ptr` then add-on-binder type signature will remain fixed.

Note that most (if not any) errors and mismatches in type signature on this level will most likely result in compilation errors when you going to compile your bindings so it is not like something could goes wrong and you will never notice it.

Also please note that is easy to inspect generated code by grep-ing for your add-on-binder function name to see if it used as intended.

**Comment by lczech** [comment] 2023-01-24 04:45
Thank you for the feedback! Yes, if the holder type did not match, the compiler would catch that I hope :-) Good to know though that this is the intended behavior, so that our code can rely on that! We'll be using this then, as well as the `add_on_binder` code as exemplified above. Thank you!

**Comment by lyskov** [comment] 2023-01-25 17:54
Great! I am assuming that this is resolved so i am closing this issue for now. (feel free to re-open if you need further help)

**Closed by lyskov** 2023-01-25 17:54 UTC

**Comment by GiannisReppas** [comment] 2023-01-31 18:14
> > As for the intended usage though: Is the Example above how these are meant to be used then? In particular, my `bitvector_extra_bindings` function above?
> 
> -- yes, thats the intending usage pattern. Note that for template classes it might be more convenient to use more specific template patters like `template<class T> void bitvector_extra_bindings( pybind11::class_<T, std::shared_ptr<T> >& cl )` which will allow you to use type `T` inside the function.
> 
> Hope this helps,

Hello,

after trying to create our own bindings for a template class using the mentioned way, it seems that +add_on_binder is not able to understand the template class instance that we give.
More specifically, we are trying to create a custom binding for a matrix template class like this:

```
//config file
+add_on_binder Matrix<int> iterate_matrix

//hpp
template<class T>
inline void iterate_matrix( pybind11::class_<T, std::shared_ptr<T> >& cl )
{
        cl.def("__iter__", [](Matrix<int> mi)
                                     { return pybind11::make_iterator(mi.begin(), mi.end());  },
                       pybind11::keep_alive<0, 1>());
}
```

However, the expected line in the bindings:
```
iterate_matrix(cl);
```
isn't produced, like in the previous example.
Should the template class instance be given in a different way?

Thanks in advance,
Lucas and Giannis

**Comment by lyskov** [comment] 2023-01-31 18:35
@GiannisReppas the way you used the `add_on_binder` option is provide bindings not for template but for the concrete class `Matrix<int>` and i am guessing that Binder have not found instances of of `Matrix<int>`. So to solve this you can try:
-- 'fix' add_on_binder directive so it could be used for template class, like this: `+add_on_binder Matrix iterate_matrix`.
-- or double check how exactly Binder tries to bind `Matrix<int>` class. It possible that it actually used different type to instantiate (like `long` or some platform specific integer types)

**Comment by GiannisReppas** [comment] 2023-01-31 19:00
Hello,

Unfortunately, the results are the same even if we use it like this `+add_on_binder Matrix iterate_matrix`

the Matrix class is binded in the following way by binder:
`pybind11::class_<Matrix<int>, std::shared_ptr<Matrix<int>>>`

As you can see, binder can find the instances of Matrix<int> , but for some reason, the +add_on_binder will be ignored

Thanks in advance

**Comment by lyskov** [comment] 2023-01-31 21:45
@GiannisReppas could you please produce minimal example to reproduce this? Thanks,

**Comment by GiannisReppas** [comment] 2023-02-01 18:38
Hello again,

after running the same example as the one you gave, it seems that binder won't read the +add_on_binder directive if the class' namespace begins with "::" (This was happening also in our case, but we made the mistake not to post it that way in order to provide a clearer example)

So, line ```+add_on_binder ::matrix_namespace::Matrix iterate_matrix``` will be ignored, but
line ```+add_on_binder matrix_namespace::Matrix iterate_matrix``` will give the expected behavior

We don't know if this is something that should be happening, but generally, it would be cool if we also had the ability to use a verbose mode, that tells you when a config file line is not used, and why not (if not already existing)

Apart from that, thank you very much for the example and for the help generally :)

Giannis and Lucas

**Comment by lyskov** [comment] 2023-02-01 20:13
Ah, i see, - glad to hear that this is resolved. And yes, this is expected behavior. Note that line `+add_on_binder ::matrix_namespace::Matrix iterate_matrix` is no ignored, it still adds specified string to list of add-on-binder's. But since string contain preceding `::` it does not match any processed classes and so it does not used.

re verbose mode: i also thought about this, - it would be indeed the nice feature to have. Let me think about this, maybe there is an elegant way to implement it.
