### ISSUE TITLE
CMake Error: The source directory "/Users/cuinjune/prefix" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by cuinjune** [RosettaCommons/binder#89] opened 2020-01-04 01:38 UTC
Hi, I'm a new user of binder and I followed [the installation steps](https://graylab.jhu.edu/Sergey/pdoc/binder/html/install.html) but when I run the last following command:

`cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_EH=1 -DLLVM_ENABLE_RTTI=ON .. && ninja`

It says: 
`CMake Error: The source directory "/Users/cuinjune/prefix" does not appear to contain CMakeLists.txt.`

Am I missing something? I followed the steps twice but still stuck at the last step.
Any guidance would be appreciated.

**Comment by cuinjune** [comment] 2020-01-11 20:10
I ask this question in Stackoverflow and I started a bounty.

https://stackoverflow.com/q/59587561/5224286

**Comment by lyskov** [comment] 2020-01-23 20:25
Thank you for reporting this @cuinjune ! I updated documentation so this issues should now be soled, could you please give it another try and see if it works for you? Thanks,

**Comment by cuinjune** [comment] 2020-01-23 21:41
@lyskov I tried it again but it fails with the same error:
`CMake Error: The source directory "/Users/cuinjune/prefix" does not appear to contain CMakeLists.txt.`

P.S: I had to put a space between `reset --` and  `hard`.

**Comment by lyskov** [comment] 2020-01-25 00:09
looks like documentation was not updated due to errors, @cuinjune could you please please follow instructions here: https://github.com/RosettaCommons/binder/blob/master/documentation/install.rst - note that final build line is changed to `cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_EH=1 -DLLVM_ENABLE_RTTI=ON ../llvm && ninja` which i think will solve this issue.

**Comment by cuinjune** [comment] 2020-01-25 20:00
I tried again and now I got the following error:

> CMake Error at tools/clang/tools/extra/CMakeLists.txt:1 (add_subdirectory):
>   add_subdirectory given source "binder" which is not an existing directory.

So I copied the `$HOME/binder` folder into `tools/clang/tools/extra` directory and tried building again.
But then I got this error:

```
CMake Error at tools/clang/tools/extra/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /Users/cuinjune/prefix/llvm/tools/clang/tools/extra/binder

  does not contain a CMakeLists.txt file.
```

**Comment by lyskov** [comment] 2020-01-29 00:24
hm... you need to _link_ Binder _binder/source_ dir there (ie `ln -s $HOME/binder/source $HOME/prefix/llvm/tools/clang/tools/extra/binder`) when you copy whole `binder` dir you copied one extra dir level...

**Comment by cuinjune** [comment] 2020-01-30 03:02
It still doesn't work with the same problem.

**Comment by lyskov** [comment] 2020-03-10 21:40
@cuinjune i just double check and can not reproduce this locally. Could you please try whole process again, preferably on a fresh clone? Also, does `build.py` works for you?

I am going to close this since i can't reproduce this issue. But feel free to re-open it if/when you have more info that could help debug this.
Thanks,

**Closed by lyskov** 2020-03-10 21:40 UTC
